### ISSUE TITLE
tclip behind proxy?

### ISSUE THREAD

**Issue by dazWiLLiE** [tailscale-dev/tclip#70]
Can I put tclip behind a proxy?

It would be much nicer to have tclip.domain.com instead of https://paste.tailxxxxx.ts.net/...

**Comment by Erisa** [comment]
Hi!

You can deploy the public-facing portion of tclip (for viewing paste links) behind a proxy by specifying the `HTTP_PORT` option and then reverse proxying that port: https://github.com/tailscale-dev/tclip?tab=readme-ov-file#configuration

Currently, it's not possible/easy to put the private tailnet-facing portion of it behind a proxy, as it needs to be accessed directly on the tailnet in order to authenticate you as a tailnet member.
